-- CreateEnum
CREATE TYPE "Colors" AS ENUM ('COLOR_DEFAULT', 'COLOR_OPTION_1', 'COLOR_OPTION_2', 'COLOR_OPTION_3', 'COLOR_OPTION_4', 'COLOR_OPTION_5', 'COLOR_OPTION_6', 'COLOR_OPTION_7', 'COLOR_OPTION_8', 'COLOR_OPTION_9', 'COLOR_OPTION_10', 'COLOR_OPTION_11', 'COLOR_OPTION_12');

-- CreateTable
CREATE TABLE "Todos" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "color" "Colors" NOT NULL DEFAULT 'COLOR_DEFAULT',
    "favorite" BOOLEAN NOT NULL DEFAULT false,
    "deleted" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Todos_pkey" PRIMARY KEY ("id")
);
