version: '3.9'
services:
  database:
    image: mysql:8
    command: mysqld --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: 'corelab-db'
    ports:
      - 3316:3306
    environment:
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=
  app:
    build: .
    container_name: corelab-api
    ports:
      - 3311:3333
    volumes:
      - .:/usr/src/corelab-challenge-api
    links:
      - database
    depends_on:
      - database
    command: sh -c "/wait; npm i; npm run db:create; npm run seed:run; npm run start:dev"
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_TIMEOUT=500
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=500