version: '3.9'

services:
  db: 
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}