version: "3.7"

services:
  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
    networks:
      - api
    # depends_on:
    #   - db

networks:
  api:
    driver: bridge
