services:
  app:
    build: .
    container_name: adonis_app
    restart: always
    env_file:
      - .env
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - ./:/app
    environment:
      PG_HOST: db

  db:
    image: postgres:13
    container_name: adonis_db
    restart: always
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: adonis_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
