services:
  app:
    build: .
    container_name: adonis-corelab-api
    ports:
      - '3333:3333'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      NODE_ENV: development # Set use of .env file
    command: >
      sh -c "
        node ace migration:run &&
        npm run dev
      "
      # This command runs migrations before starting the app and set HOST=0.0.0.0 and DB_HOST=db.

  db:
    image: postgres:17
    container_name: adonis-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: corelabdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
