version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: task-manager-mysql-db
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
