version: '3.8'

services:
  app:
    build: .
    container_name: corelab-api
    restart: always
    ports:
      - '4444:3000'
    environment:
      - NODE_ENV=production
      - MONGO_URL= ${MONGODB_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
