FROM node:18-alpine

WORKDIR /app

# Install dependencies for development
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3334

# Start in development mode
CMD ["npm", "run", "start:dev"]