version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container0-
    environment:
      MONGO_INITDB_ROOT_USERNAME: seu_login
      MONGO_INITDB_ROOT_PASSWORD: sua_senha
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data:




