version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: colab_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: testeColab
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

