
# @name create-task
POST http://localhost:3333/task/createTask
Content-Type: application/json

{
      "title": "Fazer os deveres de casa",
      "description": "Arrumar a sala e o quarto",
      "isFavorite": false,
      "color": "#123"
}


###
# @name get-all-task
GET  http://localhost:3333/task/

###

# @name create-task
POST http://localhost:3333/task/editTask/4
Content-Type: application/json

{
      "title": "Fazer os deveres de casa",
      "description": "Arrumar a sala",
      "isFavorite": false,
      "color": "#123"
}