version: '3'

services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile.api
    ports:
      - "3333:3333"
    depends_on:
      - db

  db:
    build:
      context: ./database
      dockerfile: Dockerfile.db
    ports:
      - "3312:3306"
