version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  corelab-backend:
    image: corelab-web-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 5000:5000
    links:
      - mongo
    depends_on:
      - mongo
